/**:
  ros__parameters:
    image_transport: raw
    family: 36h11
    size: 0.162
    max_hamming: 0

    detector:
      threads: 1
      decimate: 1.0
      blur: 0.0
      refine: true
      sharpening: 0.25
      debug: false

    pose_estimation_method: "pnp"

    # Optional: restrict to known IDs
    # tag:
    #   ids: [0]
    #   frames: [tag_0]
    #   sizes: [0.162]
